In [77]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.1.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [78]:
import numpy as np

# Each value 1,2,3 is a Scalar/0-D array)
# arr is a 1-D array
arr = np.array([1,2,3])

# TO create a scalar/ 0-D arrray
arr2 = np.array(42)

In [79]:
print(arr, arr2)

[1 2 3] 42


In [80]:
(type(arr))

numpy.ndarray

In [81]:
#Create a 2-D array (matrix)
mat = np.array([[1,2,3],[3,4,5]])

In [82]:
print(mat)

[[1 2 3]
 [3 4 5]]


In [83]:
# Print dimensions of arr
print(mat.ndim)

2


In [84]:
# 3-D arr
threedarr = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])

In [85]:
threedarr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [86]:
threedarr.ndim

3

In [87]:
print(threedarr.shape)

(2, 2, 3)


In [88]:
#Reshape from 1-D array with 12 elements to a 2-D array
# 4 arrays with 3 elements each
arr3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr3 = arr3.reshape(4,3)
print(newarr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [89]:
# Flatten array
newarr3.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [90]:
a5 = np.array([1,2,3,4,5])

In [91]:
a5.shape

(5,)

In [92]:
b = np.array([[1,2,3,4],[5,6,7,8]])

In [93]:
b.shape

(2, 4)

# ARRAY INDEXING

In [94]:
arrindex = np.array([3,4,5,6])

In [95]:
arrindex

array([3, 4, 5, 6])

In [96]:
arrindex.ndim

1

In [97]:
arrindex[0]

3

In [98]:
arrindex[3]

6

In [99]:
arrindex[0] + arrindex[3]

9

In [100]:
arrindex[1+1]

5

In [101]:
# 2 D array access
twodimarr1 = np.array([[1,2,3,4,5], [4,5,6,7,8]])

In [102]:
print(twodimarr1)

[[1 2 3 4 5]
 [4 5 6 7 8]]


In [103]:
# Access element from 2nd row 5th column
print(twodimarr1[1,4])

8


# Iterating arrays

In [104]:
# 1 - D array
for x in arrindex:
    print(x)

3
4
5
6


In [105]:
# 2 - D array
for x in twodimarr1:
    print(x)
print()
# Need nested for loop to look at each scalar of a matrix
for x in twodimarr1:
    for y in x:
        print(y)

[1 2 3 4 5]
[4 5 6 7 8]

1
2
3
4
5
4
5
6
7
8


# Array Slicing

In [106]:
arr6 = np.array([1,2,3,4,5,6,1])

In [107]:
# Slices arguments present between these two indices (]
arr6[1:5]

array([2, 3, 4, 5])

In [108]:
#Slices scalars from indices [1 - 7) and jumpys by 2
arr6[1:7:2]

array([2, 4, 6])

In [109]:
# slicing for 2-D array
# taken from 2 array, displaying elements at indices [1 - 4), step 2
twodimarr1[1, 1:4:2]

array([5, 7])

# Searching & Sorting Array

In [110]:
x = np.where(arr6 == 1)

In [111]:
print(x)

(array([0, 6], dtype=int64),)


In [113]:
#Find indices where values are even
x = np.where(arr6%2 == 0)
print(x)

(array([1, 3, 5], dtype=int64),)


In [117]:
# Sorting arrays - np.sort([array])
jawn = np.array([3,6,2,4,7,1,8,4])

In [115]:
jawn

array([3, 6, 2, 4, 7, 1, 8, 4])

In [116]:
np.sort(jawn)

array([1, 2, 3, 4, 4, 6, 7, 8])

In [118]:
np.sort([2,3,55,64,2,2,2,4,5,3,2])

array([ 2,  2,  2,  2,  2,  3,  3,  4,  5, 55, 64])

In [119]:
strings = np.array(["jawn", "hello", "apple"])

In [120]:
np.sort(strings)

array(['apple', 'hello', 'jawn'], dtype='<U5')

In [123]:
np.where(strings == "hello")

(array([1], dtype=int64),)